### PR TITLE
Jdk9 support

### LINKED ISSUE #390: Gretty does not work with Java 9
The stack trace after running `gradle farmStart`:

```
Exception in thread "main" java.lang.NullPointerException: Cannot invoke method getText() on null object
        at org.codehaus.groovy.runtime.NullObject.invokeMethod(NullObject.java:91)
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:48)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
        at org.codehaus.groovy.runtime.callsite.NullCallSite.call(NullCallSite.java:35)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
        at org.akhikhl.gretty.Runner.initLogback(Runner.groovy:65)
        at org.akhikhl.gretty.Runner$initLogback.callStatic(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:56)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:194)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:206)
        at org.akhikhl.gretty.Runner.run(Runner.groovy:115)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:210)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:71)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117)
        at org.akhikhl.gretty.Runner.main(Runner.groovy:44)
Exception in thread "Thread-69" org.gradle.process.internal.ExecException: Process 'command '/usr/lib/jvm/java-9-jdk/bin/java'' finished with non-zero exit value 1
        at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNormalExitValue(DefaultExecHandle.java:382)
        at org.gradle.process.internal.DefaultJavaExecAction.execute(DefaultJavaExecAction.java:31)
        at org.gradle.api.internal.file.DefaultFileOperations.javaexec(DefaultFileOperations.java:182)
        at org.gradle.api.internal.project.DefaultProject.javaexec(DefaultProject.java:1066)
        at org.gradle.api.internal.project.DefaultProject.javaexec(DefaultProject.java:1061)
        at org.gradle.api.Project$javaexec$11.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
        at org.akhikhl.gretty.DefaultLauncher.javaExec(DefaultLauncher.groovy:89)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:384)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:69)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:154)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:166)
        at org.akhikhl.gretty.LauncherBase$_launchThread_closure4.doCall(LauncherBase.groovy:256)
        at org.akhikhl.gretty.LauncherBase$_launchThread_closure4.doCall(LauncherBase.groovy)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
        at groovy.lang.Closure.call(Closure.java:414)
        at groovy.lang.Closure.call(Closure.java:408)
        at groovy.lang.Closure.run(Closure.java:495)
        at java.base/java.lang.Thread.run(Thread.java:844)
```

Or am I doing something wrong?

### PR DESCRIPTION
**Pull request by javabrett**
Incorporates and supersedes #398. Fixes #390 .

### CODE REVIEW

**Comment by boris-petrov** [comment]
@javabrett - thanks so much for your work on this! I'm not sure that this is ever going to be merged though as I'm not sure Gretty is still alive. Would you consider forking it and releasing to Maven Central?

**Comment by javabrett** [comment]
@boris-petrov we should hear from @akhikhl who is BDFL.  Are you looking for additional collaborators on the project?  I typically do not favour creating forks.

**Comment by boris-petrov** [comment]
@javabrett - I also hate *using* forks but in this case I don't see any other way. @akhikhl is not responding to any of the issues or pull-requests here so we can assume he isn't going to help with this project any time soon. A lot of people are depending on Gretty so the wisest thing to do is someone else to continue supporting it.

Actually the same happened an year or so ago - Gretty was unsupported and we started using [another fork](https://github.com/saladinkzn/gretty) of it (which had releases in Maven) and then we switched back to the original when it was resurrected. I see nothing wrong with that - the most important thing is that this project is kept alive.

**Comment by henrik242** [comment]
Noone has heard from @akhikhl since Jun 27 2017 ( https://github.com/akhikhl/gretty/issues/375#issuecomment-312020390 ), so I'm in support for a fork as well.

**Comment by boris-petrov** [comment]
And the fork should also integrate https://github.com/akhikhl/gretty/pull/415 in order to work with Gradle 4.6.

**Comment by henrik242** [comment]
Hmm, somehow gretty fails for JDK8 now, while JDK9 works.  It's groovy related:

```
Error: Could not find or load main class 
Exception in thread "Thread-235" org.gradle.process.internal.ExecException: Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_152.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1
        at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNormalExitValue(DefaultExecHandle.java:389)
        at org.gradle.process.internal.DefaultJavaExecAction.execute(DefaultJavaExecAction.java:36)
        at org.gradle.api.internal.file.DefaultFileOperations.javaexec(DefaultFileOperations.java:183)
        at org.gradle.api.internal.project.DefaultProject.javaexec(DefaultProject.java:1077)
        at org.gradle.api.internal.project.DefaultProject.javaexec(DefaultProject.java:1072)
        at org.gradle.api.Project$javaexec$14.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
        at org.akhikhl.gretty.DefaultLauncher.javaExec(DefaultLauncher.groovy:89)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:384)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:69)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:154)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:166)
        at org.akhikhl.gretty.LauncherBase$_launchThread_closure4.doCall(LauncherBase.groovy:256)
        at org.akhikhl.gretty.LauncherBase$_launchThread_closure4.doCall(LauncherBase.groovy)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
        at groovy.lang.Closure.call(Closure.java:414)
        at groovy.lang.Closure.call(Closure.java:408)
        at groovy.lang.Closure.run(Closure.java:495)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by javabrett** [comment]
> Hmm, somehow gretty fails for JDK8 now, while JDK9 works. It's groovy
related:

> Error: Could not find or load main class
> Exception in thread "Thread-235" org.gradle.process.internal.ExecException: Process 'command '/Library/Java/ JavaVirtualMachines/jdk1.8.0_152.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1
>        at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNormalExitValue(DefaultExecHandle.java:389)
>        at org.gradle.process.internal.DefaultJavaExecAction.execute(DefaultJavaExecAction.java:36)
>        at org.gradle.api.internal.file.DefaultFileOperations.javaexec(DefaultFileOperations.java:183)
>        at org.gradle.api.internal.project.DefaultProject.javaexec(DefaultProject.java:1077)
>        at org.gradle.api.internal.project.DefaultProject.javaexec(DefaultProject.java:1072)
>        at org.gradle.api.Project$javaexec$14.call(Unknown Source)
>        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
>        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
>        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
>        at org.akhikhl.gretty.DefaultLauncher.javaExec(DefaultLauncher.groovy:89)

@henrik242 do you have a simple test-case for that?

**Comment by henrik242** [comment]
@javabrett I quickly deleted that comment, it was an error in my config :)

**Comment by woldie** [comment]
Fork it @javabrett, you're our only hope!  You gotta come up with a really good name though.  How about Bretty?  :)  And please also merge my #418 PR if that works for you.

**Comment by javabrett** [comment]
@henrik242 OK that will teach me to reply via email :).  Deleted that comment too.

**Review by henrik242 — APPROVED** [review]

**Comment by henrik242** [comment]
> Fork it @javabrett, you're our only hope! You gotta come up with a really good name though. 

No need to change the name IMHO.  But there's a lot of activity on gretty now, so we should just decide on someone to maintain a fork before all the enthusiasm dwindles...

**Comment by javabrett** [comment]
@woldie @henrik242 @akhikhl I'm not especially interested in taking-up sole-maintainer role of a fork, but obviously happy to contribute.  A [GitHub Organization](https://help.github.com/articles/about-organizations/) seems like a better choice ... and then looking for others to join the cause. 
 @gretty is already taken as a username and is active.  Names?  `gretty-gradle-plugin`?

Perhaps dependent on that naming, a new plugin Maven package name is required, also assuming @akhikhl can't join and/or yield the current eponymous plugin package-name.

**Comment by woldie** [comment]
@javabrett @henrik242 @akhikhl I agree that a github organization makes sense.  Would be good to share the load and to enable a maintainer to transition ownership to other invested parties once they need to fall off.

Yes, I think a rename makes sense - more importantly, I think abandoning the existing Gretty project makes sense, and I move that we agree to do this.  "Bretty" is just a fun riff on the old name and keeping the name similar would be an indication to users that Gretty was superceded.  And if you found the Github organization, then you should get dibs on the name anyhow.  :)  

Being serious for a moment though, it *is* tremendously healthy to have a BDFL on these types of projects to point everyone at the architectural north star.  Naming after yourself is a good way to establish your turf from the get-go and yet keep it light-hearted.  Please consider this.  Of course others like myself would be willing to pitch in on approving PR's and be a part of your organization, so you will not be on your own.  But, if you wanted to be the front-man, manage releases, and otherwise delegate the work, that could be arranged given how large the community of users is.

If fun isn't what we're looking for in a name, then the new name should be very bureaucratic and descriptive.  "Tomcat Gradle Plugin" and "Jetty Gradle Plugin", or TGP and JGP.  And yes, I'm also suggesting that we separate Gretty into two plugins.  This codebase seems a bit tortured at times trying to support both vendors.

Once the new plugin is published, we should move ASAP to sunset mentions of gretty in the gradle docs and on plugins.gradle.org in favor of our new plugin.

**Comment by henrik242** [comment]
We can continue the fork discussion in https://github.com/akhikhl/gretty/issues/423

Or at https://github.com/gretty-gradle-plugin/gretty, obviously :)

**Comment by jonatanloya** [comment]
Hello Guys, Is this change available now?
Thanks a lot for the support!

**Pull request closed without merging**
