### PR TITLE
Bug fix for #192 - replace root contextPath values with "" for tomcat

### PR DESCRIPTION
**Pull request by tkent**
This is the pull request associated with #192. I decided to make this a tomcat-only patch.

### CODE REVIEW

**Comment by tkent** [comment]
/nudge @akhikhl - mind dropping this pull request in?

**Comment by ghar** [comment]
I would benefit from this pull request as well.

**Comment by tomave** [comment]
Thanks for the fix @tkent . My team and I had the same problem. Any update about accepting this pull request @akhikhl ?

**Comment by akhikhl** [comment]
Was fixed in Gretty 1.2.5 released by @saladinkzn . Will be available in mainstream Gretty 1.4.0.

**Pull request closed without merging**
